<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NitroCloud.Domain\NitroCloud.Domain.csproj" />
    <ProjectReference Include="..\NitroCloud.Shared\NitroCloud.Shared.csproj" />
  </ItemGroup>

</Project>
